<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateExpenseDescriptionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('expense_descriptions', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('categoria');
            $table->string('descripcion');
            $table->integer('estado')->default('1');
            $table->timestamps();
        });

        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Prev Plan 15'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'8', 'descripcion'=>'Aceite'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Bateria'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'5', 'descripcion'=>'Instalacion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'8', 'descripcion'=>'Filtro Aire'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'8', 'descripcion'=>'Filtro Aceite'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'8', 'descripcion'=>'Shell Helix'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'19', 'descripcion'=>'Administracion Octubre 2018'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'13', 'descripcion'=>'Cambio Filtro'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Bombillos'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Juego Pastilas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Mano de Obra'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Guardapolvo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Kit Embrague'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'5', 'descripcion'=>'Subscripcion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'13', 'descripcion'=>'Gas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Puntas ejes'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Manija'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Kit Clutch Atos'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'12', 'descripcion'=>'Rodamiento'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Encendedor'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'13', 'descripcion'=>'Cambio Equipo de gas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Emulador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'28', 'descripcion'=>'Alineacion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Bujias'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Servicio Scanner'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Halogeno'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'5', 'descripcion'=>'Cuadrar Minima'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'6', 'descripcion'=>'Llantas (2)'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'5', 'descripcion'=>'Ajuste Emulador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'13', 'descripcion'=>'Pila Bomba Gas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'14', 'descripcion'=>'SOAT'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'BZM 1509'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Escobillas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Bujes Arranque'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Switch Interruptor Bomba Gasolina'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Juego Bandas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Cambio de Bandas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Rectificacion de Campanas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Llave duplicado'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'16', 'descripcion'=>'Revision Tecnomecanica'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Empaquetadura Motor'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Pera Aceite'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Pera Temperatura'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Correa Reparticion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Tensor Correa'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Silicona'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Correa Alternador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Bomba Agua'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Manguera Bomba Agua'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Manguera Calefaccion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Casquetes Biela Bancada'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Media Lunas std'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Valvulas Admision y Escape'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Sellos Valvulas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Anillos'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Soporte Motor Trasero'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Termostato'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Bomba Aceite'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Manguera Booster'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Empaque Tapa Valvulas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Abrazaderas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Mangueras Agua'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Guias Valvulas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Juego Pistones'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Aceite y Filtros'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Lavado Inyectores'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Rectificar Bloque'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Rectificar Cigueñal'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Rectificar Culatas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Ensamblar Pistones'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Sentar y Armar Valvulas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Lavar Motor'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Circulo de Bancada Biela'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Carcaza'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Fusible'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Bandas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Bocin Trasero'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'21', 'descripcion'=>'Caja de direccion GTI completa'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Puños (2)'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Axial'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Tornillo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Reten Toma'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Gasolina'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Punta L/R Atos lado conductor'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'13', 'descripcion'=>'Gasto Gasolina Corrient Oxigenada'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'18', 'descripcion'=>'Traspaso'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'22', 'descripcion'=>'Instalacion Pila Gasolina'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'22', 'descripcion'=>'Pila Gasolina'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Instalacion de Alta PCY'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'13', 'descripcion'=>'Revision Annual'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'5', 'descripcion'=>'Combustible'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'3', 'descripcion'=>'Seguro Extracontractual'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Bobina'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'30', 'descripcion'=>'Revision'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Ventilador Radiador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'19', 'descripcion'=>'Administracion Noviembre 2018 - Enero 2019'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Pastillas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'25', 'descripcion'=>'Tapa y Empaque radiador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'25', 'descripcion'=>'Motor y Ventilador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'25', 'descripcion'=>'Tapa Radiador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Rectificacion Bases y Valvulas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Cambio Guias'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Armadas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Empaque Culata'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Empaque Multiple Admision'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Reten Eje de Levas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'6', 'descripcion'=>'Rotacion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Libre'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Desbarada'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'12', 'descripcion'=>'Tramite'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Revision Preventiva'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Fotocopias'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Tarjetas de Control'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Autenticacion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Parqueo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'20', 'descripcion'=>'Patios'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'12', 'descripcion'=>'Febrero & Marzo 2019'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'12', 'descripcion'=>'Tarjeta de Operacion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'30', 'descripcion'=>'Reparacion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Bombillos Stop'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Mantenimiento Chapa'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'6', 'descripcion'=>'Llanta'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Laminacion Tarjeton'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Planilla de Viaje'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Valvula IAC'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Rotula'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Axiales (2)'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Muñecos'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Inyector'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Elevador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'11', 'descripcion'=>'Bujes Palanca Cambios'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'11', 'descripcion'=>'Manguera Desague'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Revision Alternador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Revision arranque'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Cambio Bujes'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'6', 'descripcion'=>'Montaje'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'24', 'descripcion'=>'Juego Bujes Cuña Arandelas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'24', 'descripcion'=>'Bujes Puño'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'24', 'descripcion'=>'Soporte Palanca de Cambios'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'24', 'descripcion'=>'Buje Soporte Motor'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'24', 'descripcion'=>'Tornillos'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'24', 'descripcion'=>'Reforzar y Soldar Cuña'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Sello'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Sensor Velocidad'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'19', 'descripcion'=>'Administracion Abril 2019'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'27', 'descripcion'=>'Seguridad Social'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'23', 'descripcion'=>'Impuestos'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Yukkazzo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'8', 'descripcion'=>'Cambio de Aceite'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'13', 'descripcion'=>'Calibracion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Instalacion de Alta'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Punta L/R'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Amortiguador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Bombillo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Pin de Eje'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Punta L/C'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Bocin delantero'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Abrazadora'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Pin cacho'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Guaya Acelerador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'8', 'descripcion'=>'Ace'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Bloque Tapones'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Probar Bancada y Biela'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Lavado'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Culata de Atos, alternador y multiple'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Asco gasolina'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Probar Inyectores'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Electrico pacha'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Cambio Flexible'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Calibracion Analizador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Pistones'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Camisas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Empaquetura del motor'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Kit Reparacion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Erosol Negro'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Filtro Aceite y Aire'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Inyectores'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Mantenimiento Aceleracion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Mantenimiento Frenos'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Empaquetura valvulas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Kit Reparacion correa'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Manguera 30 cm'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'26', 'descripcion'=>'Soldadura'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'26', 'descripcion'=>'Cambio anillo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Conectores'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Analisis de gases'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Campanas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Graduacion frenos'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'29', 'descripcion'=>'Revi'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Cilindro'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Sensor de Oxigeno'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Scannear'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Calibrada valvulas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'19', 'descripcion'=>'Administracion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'6', 'descripcion'=>'Vulcanuzacion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'17', 'descripcion'=>'Puerta remplazo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'21', 'descripcion'=>'Caja'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'21', 'descripcion'=>'Valvulina'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'21', 'descripcion'=>'Retenedor'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'6', 'descripcion'=>'Balanceo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Eje Izquierdo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'2 Libras de Grasa'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'8 Abrazaderas Plasticas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Cauchos para estabilizadora'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Kit de Clutch'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Reten Volante'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'2 Cuartos de Valvulina'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'2 Abrazaderas aceradas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Suavizador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Guaya Clutch'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Pernos con Tuercas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'13', 'descripcion'=>'Hidrostatica CO2'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'13', 'descripcion'=>'Contenedor'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Reten Piñon velocimetro'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Pinta liquido de Freno'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Empaque'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Juego Plumillas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'13', 'descripcion'=>'Legalizacion Regulador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Pluma Metalica'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Aspirales Reforzados'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Amortiguadores'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Mogollas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Liquido'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'26', 'descripcion'=>'Alquiler catalizador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Revision Inyeccion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Espirales'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Miscelaneo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Teja ventana'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Bombillo Techo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'11', 'descripcion'=>'Piñones'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'11', 'descripcion'=>'Kiy bujes barra de cambios'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'11', 'descripcion'=>'Murcielagos'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'11', 'descripcion'=>'Tuercas y esparragos'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'11', 'descripcion'=>'Cuarto de Aceite'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'11', 'descripcion'=>'Escaniada'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Duplicado'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'19', 'descripcion'=>'Calcomanias'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Papel humedo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Manijas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Automatico de Arranque'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Switch Ignicion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Pera Agua'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Correa'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Buje Guaya'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Empaque Exhosto'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Eje Levas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Romula Daewoo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Rosca Helice'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Kit Repaticion'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Grasa Clutch'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'13', 'descripcion'=>'Revision Hidrostatica'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Cambio pera'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Manguera '));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Pachas'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Poder'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'11', 'descripcion'=>'Pujo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'11', 'descripcion'=>'Rodamientos'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Sonda Lambda'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Tijera'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Piñon Velocimetro'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Topes'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Kit bujes'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Cables'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Coraza'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Pin'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Grua'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Arreglo Farola'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Switch parqueo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Flasher'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Bajado de arranque'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Conector de Pacha'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Tapa Termostato'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Terminal'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Pera Reverso'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Rodamientos (2)'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Tapetes'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Soporte Amortiguador'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Pacha'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Retencion Control Cambios'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Pera de reverso'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Bocin'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Switch'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Instalacion Yukazo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Reten Polea'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Sensor de Minima'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Ajuste Manguera'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Buje Tijera'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Placa Lateral'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Reten Aceite'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Liga'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Manguera Codo'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Reten Eje'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Tubo trasero termostato'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'1', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'2', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'3', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'4', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'5', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'6', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'7', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'8', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'9', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'10', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'11', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'12', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'13', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'14', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'15', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'16', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'17', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'18', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'19', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'20', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'21', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'22', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'23', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'24', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'25', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'26', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'27', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'28', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'29', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'30', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'31', 'descripcion'=>'Otro Servicio'));
        DB::table('expense_descriptions')->insert(array('categoria'=>'32', 'descripcion'=>'Otro Servicio'));
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('expense_descriptions');
    }
}
